---
- name: Размещение PHP проекта на тестовом сервере
  hosts: test-server
  become: yes

  tasks:

    - name: Удаляем предыдущую версию проекта
      file:
        path: /var/www/html/php-app
        state: absent

    - name: Копируем новую версию проекта
      synchronize:
        src: ../php-app/
        dest: /var/www/html/php-app/
        rsync_opts:
          - "--delete"

    - name: Устанавливаем права на директорию
      file:
        path: /var/www/html/php-app
        state: directory
        owner: www-data
        group: www-data
        recurse: yes

    - name: Перезапускаем Apache
      service:
        name: apache2
        state: restarted
