---
- hosts: testserver
  become: yes
  tasks:

    - name: Обновление пакетов
      apt:
        update_cache: yes

    - name: Установка Apache
      apt:
        name: apache2
        state: present

    - name: Установка PHP и расширений
      apt:
        name:
          - php
          - php-cli
          - php-mbstring
          - php-xml
          - php-curl
          - php-zip
          - php-mysql
        state: present

    - name: Перезагрузка Apache
      service:
        name: apache2
        state: restarted
