FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    openssh-server \
    git \
    php-cli php-xml php-zip php-mbstring \
    unzip \
    && mkdir -p /var/run/sshd

# User for SSH
RUN useradd -m -s /bin/bash jenkins

# SSH keys
RUN mkdir -p /home/jenkins/.ssh
COPY secrets/ssh-agent-key.pub /home/jenkins/.ssh/authorized_keys
RUN chmod 600 /home/jenkins/.ssh/authorized_keys && \
    chown -R jenkins:jenkins /home/jenkins/.ssh

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
