FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# Установка Apache + PHP + SSH + базовые пакеты
RUN apt-get update && apt-get install -y \
    tzdata \
    apache2 \
    php \
    libapache2-mod-php \
    php-mysql \
    openssh-server \
    sudo \
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Создаём пользователя ansible
RUN useradd -m ansible && echo "ansible ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Настройка SSH
RUN mkdir /var/run/sshd

RUN mkdir -p /home/ansible/.ssh \
    && chmod 700 /home/ansible/.ssh \
    && chown -R ansible:ansible /home/ansible/.ssh

# Настройка Apache
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf

EXPOSE 22 80

# Запуск Apache + SSH
CMD service apache2 start && /usr/sbin/sshd -D
