FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    openssh-server \
    ansible \
    sudo \
    && rm -rf /var/lib/apt/lists/*

# user ansible
RUN useradd -m ansible && echo "ansible ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# ssh config
RUN mkdir -p /home/ansible/.ssh && \
    chmod 700 /home/ansible/.ssh && \
    chown -R ansible:ansible /home/ansible/.ssh && \
    mkdir /var/run/sshd

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
