FROM php:8.2-cli

RUN apt-get update && apt-get install -y \
    openssh-server \
    git \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Install Composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php composer-setup.php --install-dir=/usr/local/bin --filename=composer && \
    rm composer-setup.php

# Create Jenkins user
RUN useradd -m jenkins

RUN mkdir -p /var/run/sshd

RUN mkdir -p /home/jenkins/.ssh \
    && chown -R jenkins:jenkins /home/jenkins/.ssh \
    && chmod 700 /home/jenkins/.ssh

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
